version: "3"
services:
  postgres:
    image: postgis/postgis
    container_name: 'postgressql-infobes'
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      LANG: "C"
      LC_CTYPE: "C"
      LC_COLLATE: "C"
    volumes:
      - ./psql-ext.sql:/docker-entrypoint-initdb.d/psql_ext.sql
      - .:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready -U test' ]
      interval: 5s
      timeout: 5s
      retries: 5